### PR TITLE
Fix residentialAddress being lost after selecting pickup point

### PR DESCRIPTION
**Pull request by marcoskwkm**
#### What is the purpose of this pull request?
When the user selects a pickup point in the modal, it sends a `shippingData` attachment request to the API with the selected address. However, it does not send the currently active residential address as an element of `selectedAddresses` in the request, and that makes the API use the search address for all products in the cart. This PR fixes this issue by making the modal send the residential address as well.

This should be reviewed along with https://github.com/vtex/pickup-points-modal/pull/136.

#### How should this be manually tested?
***Case 1: First purchase***
1. Add these two items to cart. ([vtexgame1](https://pickup2p--vtexgame1.vtexcommercestable.com.br/checkout/cart/add?sku=289&qty=1&seller=1&sc=1&sku=285&qty=1&seller=1&sc=1)/[clean](https://pickup2p--vtexgame1clean.vtexcommercestable.com.br/checkout/cart/add?sku=289&qty=1&seller=1&sc=1&sku=285&qty=1&seller=1&sc=1)/[geo](https://pickup2p--vtexgame1geo.vtexcommercestable.com.br/checkout/cart/add?sku=289&qty=1&seller=1&sc=1&sku=285&qty=1&seller=1&sc=1)/[invoice](https://pickup2p--vtexgame1invoice.vtexcommercestable.com.br/checkout/cart/add?sku=289&qty=1&seller=1&sc=1&sku=285&qty=1&seller=1&sc=1)/[nolean](https://pickup2p--vtexgame1nolean.vtexcommercestable.com.br/checkout/cart/add?sku=289&qty=1&seller=1&sc=1&sku=285&qty=1&seller=1&sc=1))
2. Use a new email and proceed to shipping.
3. Search for a pickup point in Botafogo. Before clicking "retirar neste ponto", open your Network tab and filter for `shippingData` requests.
4. Click "retirar neste ponto". A `shippingData` request should be sent. It should succeed (this means the modal did not send an empty residential address to the API).

***Case 2: Second purchase***
1. Add these two items to cart. ([vtexgame1](https://pickup2p--vtexgame1.vtexcommercestable.com.br/checkout/cart/add?sku=289&qty=1&seller=1&sc=1&sku=285&qty=1&seller=1&sc=1)/[clean](https://pickup2p--vtexgame1clean.vtexcommercestable.com.br/checkout/cart/add?sku=289&qty=1&seller=1&sc=1&sku=285&qty=1&seller=1&sc=1)/[geo](https://pickup2p--vtexgame1geo.vtexcommercestable.com.br/checkout/cart/add?sku=289&qty=1&seller=1&sc=1&sku=285&qty=1&seller=1&sc=1)/[invoice](https://pickup2p--vtexgame1invoice.vtexcommercestable.com.br/checkout/cart/add?sku=289&qty=1&seller=1&sc=1&sku=285&qty=1&seller=1&sc=1)/[nolean](https://pickup2p--vtexgame1nolean.vtexcommercestable.com.br/checkout/cart/add?sku=289&qty=1&seller=1&sc=1&sku=285&qty=1&seller=1&sc=1))
2. Use `marcos@mailinator.com` as email.
3. Search and select a pickup point in Botafogo.
4. Click "Preencher entrega". There should be only one SLA available (this means the modal sent the residential address to the API).

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Comment by darlenedms** [comment]
For some reason on `vtexgame1` after clicking on "Preencher entrega" the only address available is not auto-selected. All os the other accounts worked properly. Any ideia?

Screen Shot 2020-05-07 at 6 53 05 PM

**Comment by marcoskwkm** [comment]
> For some reason on `vtexgame1` after clicking on "Preencher entrega" the only address available is not auto-selected. All of the other accounts worked properly. Any ideia?

Yes, that's the bug this PR tries do solve in the first place. Note how the SLAs being shown correspond to the search address (Botafogo), and not the residential address (Sao Paulo), which has only one SLA available.

Guess what, the changes were not linked in the `vtexgame1` workspace 🤦 

It should be working now.

**Comment by lucasecdb** [comment]
@marcoskwkm the available address still is not auto-selecting in vtexgame1 :-/

**Comment by marcoskwkm** [comment]
> @marcoskwkm the available address still is not auto-selecting in vtexgame1 :-/

I identified a bug when running the E2E tests and fixed it, but that made my initial solution not work anymore /o\\
It should be fixed now. I added the scenario I've found to the test plan and tested again in all accounts. I'm also running the E2E tests again to see if anything new pops up.

**Pull request merged**
